apiVersion: apps/v1
kind: Deployment
metadata:
  name: inrad-api
  labels:
    app: inrad-api
spec:
  selector:
    matchLabels:
      app: inrad-api
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: inrad-api
        tier: backend
    spec:
      containers:
        - image: alexaxms/inrad-api:cac5527
          name: inrad-api
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: db_host
            - name: APP_HOST
              value: http://inrad.musicmania.cl/
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: db_name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: db_password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: db_username
            - name: RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: rabbit_host
            - name: PYTHONUNBUFFERED
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: pythonunbuffered
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: django_superuser_password
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: django_superuser_username
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: django_superuser_email
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: secret_key
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: aws_secret_access_key
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: aws_storage_bucket_name
            - name: AWS_S3_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: inrad-api-secret
                  key: aws_s3_region_name
          ports:
            - containerPort: 8000
              name: inrad-api
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"