apiVersion: apps/v1
kind: Deployment
metadata:
  name: inrad-api
  labels:
    app: inrad-api
spec:
  selector:
    matchLabels:
      app: inrad-api
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: inrad-api
        tier: backend
    spec:
      containers:
        - image: alexaxms/inrad-api:cac5527
          name: inrad-api
          envFrom:
          - secretRef:
              name: inrad-api-secret
          - configMapRef:
              name: api
          ports:
            - containerPort: 8000
              name: inrad-api
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "500m"